server:
  # 配置api端口号
  port: 8088
  # session最大超时时间(分钟)，默认为30分钟
  session-timeout: 60
  # 配置context-path, 一般来说这个配置在正式发布的时候不配置
  servlet:
    context-path: /service

spring:
  zipkin:
    base-url: http://localhost:9411

#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
